FROM oven/bun:1 AS base
WORKDIR /home/luke/mp-xfiapp

RUN mkdir -p /usr/src/mp-xfiapp
COPY package.json bun.lock /usr/src/mp-xfiapp/
RUN bun install && bun install next
COPY . .
ENV NODE_ENV=production
# # RUN bun test
RUN bun run build

# Final Stage: run the app
USER bun
EXPOSE 3000/tcp
CMD ["bun", "run", "start"]
